/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moc.sudoku;

import com.moc.sudoku.service.ValidationException;
import com.moc.sudoku.service.Parser;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.jupiter.api.Assertions.*;

class UsageTest {


    private final static ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final static PrintStream originalOut = System.out;


    @BeforeAll
    static void setUpStreams() {
        System.setOut(new PrintStream(outContent));
    }

    @AfterAll
    static void restoreStreams() {
        System.setOut(originalOut);
    }


    @Test
    void givenNoSolutionFileProvided_thenValidationExceptionThrownWithUsage() {
        ValidationException exception = assertThrows(ValidationException.class, () -> new Parser().load(""));
        System.out.println(exception.getMessage());
        assertTrue(outContent.toString().contains("Usage:"), "app should print Usage in case no solution file provided");
    }
}
