/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moc.sudoku;

import com.moc.sudoku.data.Grid;
import com.moc.sudoku.service.Converter;
import com.moc.sudoku.service.Parser;
import com.moc.sudoku.service.Validator;

import java.util.List;

public class App {

    private final transient Parser parser = new Parser();
    private final transient Converter converter = new Converter();
    private final transient Validator validator = new Validator();

    private void run(String fileName) {
        List<String[]> lines = parser.load(fileName);
        Grid grid = converter.loadLines(lines);
        validator.validate(grid);
    }

    public static void main(String[] args) {
        try {
            new App().run(args.length == 0 ? "" : args[0]);
        } catch (Exception e) {
            System.out.println(e.getMessage()); // NOPMD
            System.exit(1);
        }
    }

}
